### ISSUE TITLE
[Clock] Unable to load DLL 'Kernel32.dll' on Linux

### ISSUE THREAD

**Issue by michaeldimoudis** [NimaAra/Easy.Common#10]
Hi thanks for this library, stumbled upon it recently and it's got some great stuff in there 👍 

Just an issue I encountered with a .NET Core 2 app on a Raspberry Pi running Raspbian Linux (could be an issue on other linux distro's too?)

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'Kernel32.dll': The specified module or one of its dependencies could not be found.

 (Exception from HRESULT: 0x8007007E)
   at Easy.Common.NativeMethods.GetSystemTimePreciseAsFileTime(Int64& filetime)
   at Easy.Common.Clock..ctor()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCreateInstance(CreateInstanceCallSite createInstanceCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at MyApp.Program.<Main>d__1.MoveNext() in D:\Workspace\my-app-raspberry-pi\src\MyApp\Program.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyApp.Program.<Main>(String[] args)
```

Basically when I build my Service Provider, the above error occurs, so it can't fall back to non precise time. I've worked around it by copying the `Clock.cs` source code in my project and using that without `GetSystemTimePreciseAsFileTime(out preciseTime);`. Am I missing a nuget package or is there some additional work required to not throw that error on startup?

Cheers

**Comment by NimaAra** [comment]
Thanks for reporting this.

The issue has now been fixed as part of [v2.8.2](https://github.com/NimaAra/Easy.Common/releases/tag/Easy.Common-release-v2.8.2) and has also been pushed to _NuGet_ @ [Easy.Common-release-v2.8.2](https://www.nuget.org/packages/Easy.Common/2.8.2).

Please validate.

**Comment by michaeldimoudis** [comment]
Yep it works now. Thank's for the quick turnaround.

**Comment by PNAVYAREDDY1** [comment]
![image](https://user-images.githubusercontent.com/36952287/38452092-8a4dfc8e-3a5a-11e8-9eed-d2af1f401599.png)

**Comment by vishalakshisonata** [comment]
Am also facing the same issue, while creating a file am checking the safeFileHandle, there am importing this kernel32.dll. Local run i dont find any issue, i have published in docker container. When i run this through the container IP am getting the issue.

  "errorMessage": "Unable to load DLL 'kernel32.dll': The specified module or one of its dependencies could not be found.\n (Exception from HRESULT: 0x8007007E)"


  [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        static extern SafeFileHandle CreateFile(string lpFileName, uint dwDesiredAccess, uint dwShareMode, IntPtr lpSecurityAttributes, uint dwCreationDisposition, uint dwFlagsAndAttributes, IntPtr hTemplateFile);
